Imprvements, error corrections and library additions as detailed
shlibs Application 1.4.39
- improved performance and handling of calls to shlibs from inside libraries by eliminating re-testing (assumed passed)
- restored usage of absolute paths for internal code
- shlibs_dev_query.sh - corrected an error causing incorrect setup of scripts including non-official libraries using the official format
- shlibs_err.sh - corrected an error occurring when missing error.log file
- minor format corrections

shlibs Official Libraries 1.1.47
- dir002  - new addition: Create a temporary directory and return the path to it
- gen001  - new addition: Install/remove packages or show package management tools
- ip001   - new addition: Get public facing IPv4, or IPv6
- mth005  - new addition: Get a random number in interval 0-1 (adjustable precision)
- mth006  - new addition: Get a random integer in specified interval
- ofc006  - new addition: Outputs a customizable list of all available shlibs library codes
- port001 - new addition: Get random free ephemeral ports
- ofc001, ofc002, ofc003 - upgrade to release 5: changed version and release numbers

Signed-off-by: Iotu Nicolae <nicolae.g.iotu@gmail.com>

diff --git a/shlibs b/shlibs
--- a/shlibs
+++ b/shlibs
@@ -49,34 +49,37 @@
 	
 	cd "${shlibs_dirpath}" || exit 1
 	
-	. './var/comp/ptbl/shlibs_redir.sh'
+	. "${shlibs_dirpath}/var/comp/ptbl/shlibs_redir.sh"
 	if [ "${shlibs_redir_vars_flag}" = '0' ]; then
 		unset shlibs_redir_vars_flag
 		if [ "${SHLIBS_COMPLEX_PIPE}" = '0' ]; then
 			unset SHLIBS_COMPLEX_PIPE
-			./shlibs "${@}" ${shlibs_redir_vars}
+			"${shlibs_dirpath}"/shlibs "${@}" ${shlibs_redir_vars}
 		else
 			unset SHLIBS_COMPLEX_PIPE
-			./shlibs "${@}" "${shlibs_redir_vars}"
+			"${shlibs_dirpath}"/shlibs "${@}" "${shlibs_redir_vars}"
 		fi
 		exit ${?}
 	fi
 	
-	tcs='./var/comp/cap/shlibs_test_env.sh'
-	if [ -r "${tcs}" ] ; then :
+	. "${shlibs_dirpath}/var/shlibs_settings.sh"
+	if [ -n "${SHLIBS_SHELL_PATH}" ]; then :
+		# skip tests (assumed passed) if a shlibs lib calls other shlibs libs
 	else
-		if type shlibs >/dev/null 2>&1 ; then
-			echo 'Error: do not source shlibs.'
+		tcs="${shlibs_dirpath}/var/comp/cap/shlibs_test_env.sh"
+		if [ -r "${tcs}" ] ; then :
 		else
-			printf "%s %s\n" 'Error: Please make sure shlibs folder is' \
-				'included on PATH, and/or declared as SHLIBS_HOME.'
+			if type shlibs >/dev/null 2>&1 ; then
+				echo 'Error: do not source shlibs.'
+			else
+				printf "%s %s\n" 'Error: Please make sure shlibs folder is' \
+					'included on PATH, and/or declared as SHLIBS_HOME.'
+			fi
+			exit 1
 		fi
- 		exit 1
+		. "${tcs}"
 	fi
 	
-	. './var/shlibs_settings.sh'
-	. "${tcs}"
-	
 	exec "${SHLIBS_SHELL_PATH}" \
-		'./var/comp/shlibs_handover.sh' "${@}"	
+		"${shlibs_dirpath}/var/comp/shlibs_handover.sh" "${@}"
 )
